---
- hosts: TEST-GROUP
  become: yes
  become_method: sudo
  tasks:

  - name: Replace comfiguration file
    template: src=templates/foo.j2 dest=/home/ansible/file.conf owner=ansible group=wheel mode=0644
